[simulation]
  name    = "three_wave"
  engine  = "srpic"
  runtime = 100.0

  [simulation.domain]
    decomposition = [-1, -1, -1]

[grid]
  resolution = [512, 512, 512]
  extent     = [[0.0, 512.0], [0.0, 512.0], [0.0, 512.0]]

  [grid.metric]
    metric = "minkowski"

  [grid.boundaries]
    fields    = [["PERIODIC"], ["PERIODIC"], ["PERIODIC"]]
    particles = [["PERIODIC"], ["PERIODIC"], ["PERIODIC"]]

[scales]
  larmor0    = 0.5
  skindepth0 = 5.0

[algorithms]
  current_filters = 8

  [algorithms.timestep]
    CFL = 0.5

[particles]
  ppc0 = 5.0

  [[particles.species]]
    label    = "e-"
    mass     = 1.0
    charge   = -1.0
    maxnpart = 1e8

  [[particles.species]]
    label    = "e+"
    mass     = 1.0
    charge   = 1.0
    maxnpart = 1e8

[setup]
  temperature = 1e-4

  n_waves = 3

  # 1 = AW, 0 = FMS; AW modes first (they contribute ext_current)
  wave_type  = [0,    0,    1   ]
  wave_kx    = [10.0,  5.0,  5.0 ]
  wave_ky    = [0.0,  -5.0,  5.0 ]
  wave_kz    = [0.0,  5.0,  -5.0 ]
  wave_amp   = [0.3,  0.,  0.0]
  wave_phase = [0.0,  0.4, 0.7]

[output]
  format        = "bpfile"
  interval_time = 10.0

  [output.fields]
    quantities = ["N_1", "N_2", "E", "B", "J"]

  [output.particles]
    stride = 10

  [output.spectra]
    enable = true